modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="createautocrafting.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="hihellohi"
description='''Physical pattern crafting for Create logistics — Pattern Providers, Logic Coils, and virtual stock links.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.11,6.1.0)"
ordering="AFTER"
side="BOTH"
